// TEST-4 — WiFi behavioural coverage: reconnection, STA fallback timer, AP mode.
//
// Until this suite, every one of these paths was unreachable natively: the
// clock was the wall clock (a timeout test would take 15 real seconds), the
// heap was frozen at 65536 (no low-heap branch could open), and the WiFi stub
// was stateless (mode always Off, startAP always false — the skip-restart
// branch compares both against what startAP was given). The seams this suite
// drives are Platform_Stub.h's scriptable millis/heap/restart-count and
// Wifi_Stub.h's mode/AP/connect record; every seam default is byte-identical
// to the old stubs.
//
// Contract: _bmad-output/implementation-artifacts/spec-test-4-wifi-behaviour-
// coverage.md (v2 — two tests were refuted as first specified; the fixture
// rules below come from that review).
//
// Fixture invariants:
// - The millis override is installed BEFORE the component is constructed:
//   NonBlockingDelay captures getMillis() at construction, and a timer
//   anchored to the wall clock then read against an override at 0 wraps and
//   fires once spuriously.
// - F-scenarios construct with STA credentials. A default-constructed
//   component's begin() starts the autogenerated AP and poisons every
//   "no startAP" assertion downstream.
// - Counters are asserted as DELTAS snapshotted after setup — begin() and
//   pre-begin enableAP() legitimately touch the HAL before the scenario
//   starts.
// - Core::loop() is a no-op before Core::begin(); events emitted during
//   begin() are queued, not dispatched, so subscribers attach before begin()
//   and assert after one loop().

#include <unity.h>
#include <DomoticsCore/Core.h>
#include <DomoticsCore/Wifi.h>
#include <DomoticsCore/WifiEvents.h>

#include <vector>

using namespace DomoticsCore;
using namespace DomoticsCore::Components;

using HAL::WiFiHAL::Mode;

static Core* testCore = nullptr;
static WifiComponent* wifiPtr = nullptr;

// Event capture — sequences, not just last values: F3 must see AP disabled by
// the arming loop and re-enabled by the success loop, in that order.
static std::vector<bool> staEvents;
static std::vector<bool> apEvents;
static std::vector<String> readyPayloads;

// Config-save capture (STA fallback timeout and the ultra-low-heap guard both
// persist autoConnect=false to break boot loops).
static bool configSaved = false;
static WifiConfig savedConfig;

void setUp(void) {
    // Before any construction — see the fixture invariants above.
    HAL::Platform::setMillisForTest(0);
    HAL::Platform::resetFreeHeapForTest();
    HAL::Platform::resetRestartCountForTest();
    HAL::WiFiImpl::resetWifiStateForTest();
    HAL::WiFiImpl::setConnectedForTest(false);

    staEvents.clear();
    apEvents.clear();
    readyPayloads.clear();
    configSaved = false;
    savedConfig = WifiConfig();
}

void tearDown(void) {
    if (testCore) {
        testCore->shutdown();
        delete testCore;
        testCore = nullptr;
    }
    wifiPtr = nullptr;
    HAL::WiFiImpl::resetWifiStateForTest();
    HAL::WiFiImpl::resetScanForTest();
    HAL::WiFiImpl::setConnectedForTest(false);
    HAL::Platform::resetMillisForTest();
    HAL::Platform::resetFreeHeapForTest();
    HAL::Platform::resetRestartCountForTest();
}

static void subscribeAll() {
    testCore->getEventBus().subscribe(WifiEvents::EVENT_STA_CONNECTED, [](const void* p) {
        if (p) staEvents.push_back(*static_cast<const bool*>(p));
    });
    testCore->getEventBus().subscribe(WifiEvents::EVENT_AP_ENABLED, [](const void* p) {
        if (p) apEvents.push_back(*static_cast<const bool*>(p));
    });
    testCore->getEventBus().subscribe(WifiEvents::EVENT_NETWORK_READY, [](const void* p) {
        // Emitted through the sized overload, length()+1 — a NUL-terminated
        // char*, deep-copied by the bus (BUG-30's contract).
        if (p) readyPayloads.push_back(String(static_cast<const char*>(p)));
    });
}

// Core-backed STA fixture: subscribers attached, begin() run. Leaves one
// connect() call recorded and a connection in progress at t=0.
static void buildStaFixture() {
    testCore = new Core();
    subscribeAll();
    auto wifi = std::make_unique<WifiComponent>("Net", "pw");
    wifiPtr = wifi.get();
    testCore->addComponent(std::move(wifi));
    testCore->begin();
}

static void captureConfigSave(const WifiConfig& cfg) {
    configSaved = true;
    savedConfig = cfg;
}

// Arms the STA fallback timer for real (review finding 1: heap 20000 takes the
// direct AP+STA branch at Wifi.h:805 and never arms anything — every fallback
// scenario must enter through a heap in [2000, 3500)).
// On return: stopAP fired once, mode is Station, no startAP yet, t unchanged.
static void armFallbackAt3000() {
    WifiConfig cfg;
    cfg.ssid = "Net";
    cfg.password = "pw";
    cfg.autoConnect = true;
    cfg.enableAP = true;
    cfg.apSSID = "FallAP";
    cfg.apPassword = "appw";
    wifiPtr->setConfig(cfg);  // defers to loop() via pendingModeUpdate_

    HAL::Platform::setFreeHeapForTest(3000);
    const auto& st = HAL::WiFiImpl::stubWifiState();
    unsigned stopBefore = st.stopAPCalls;
    unsigned startBefore = st.startAPCalls;
    testCore->loop();

    // The arming discriminator: this branch tears the AP down to free heap for
    // the STA attempt. Without it, F2/F3/F4 would pass through other paths.
    TEST_ASSERT_EQUAL_UINT(stopBefore + 1, st.stopAPCalls);
    TEST_ASSERT_EQUAL_UINT(startBefore, st.startAPCalls);
    TEST_ASSERT_EQUAL_INT((int)Mode::Station, (int)HAL::WiFiHAL::getMode());
}

// ============================================================================
// Reconnection
// ============================================================================

void test_reconnect_success_emits_events(void) {
    buildStaFixture();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    TEST_ASSERT_EQUAL_UINT(1, st.connectCalls);  // begin() started the attempt
    TEST_ASSERT_EQUAL_STRING("Net", st.lastConnectSSID.c_str());
    TEST_ASSERT_TRUE(wifiPtr->isConnectionInProgress());

    HAL::WiFiImpl::setConnectedForTest(true);
    HAL::Platform::advanceMillisForTest(101);  // past the 100 ms poll timer
    testCore->loop();

    TEST_ASSERT_FALSE(wifiPtr->isConnectionInProgress());
    TEST_ASSERT_EQUAL_INT((int)ComponentStatus::Success, (int)wifiPtr->getLastStatus());
    TEST_ASSERT_EQUAL_INT(1, (int)staEvents.size());
    TEST_ASSERT_TRUE(staEvents[0]);
    TEST_ASSERT_EQUAL_INT(1, (int)readyPayloads.size());
    TEST_ASSERT_EQUAL_STRING("0.0.0.0", readyPayloads[0].c_str());
}

void test_connection_timeout_then_same_tick_retry(void) {
    buildStaFixture();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    HAL::Platform::advanceMillisForTest(15001);  // past CONNECTION_TIMEOUT
    testCore->loop();

    TEST_ASSERT_EQUAL_INT((int)ComponentStatus::TimeoutError, (int)wifiPtr->getLastStatus());
    TEST_ASSERT_EQUAL_INT(1, (int)staEvents.size());
    TEST_ASSERT_FALSE(staEvents[0]);
    // Deliberate behaviour pin: the retry fires in the SAME loop() as the
    // timeout — the 5 s reconnect timer is always ready when the 15 s timeout
    // fires. Reorder loop() and this red tells you the retry latency changed.
    TEST_ASSERT_EQUAL_UINT(2, st.connectCalls);
    TEST_ASSERT_TRUE(wifiPtr->isConnectionInProgress());
}

void test_disconnect_stops_reconnection(void) {
    buildStaFixture();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    HAL::Platform::advanceMillisForTest(15001);
    testCore->loop();  // timeout + same-tick retry → 2 calls
    TEST_ASSERT_EQUAL_UINT(2, st.connectCalls);

    wifiPtr->disconnect();
    unsigned before = st.connectCalls;
    HAL::Platform::advanceMillisForTest(20000);  // second attempt times out too
    testCore->loop();

    TEST_ASSERT_EQUAL_UINT(before, st.connectCalls);
    TEST_ASSERT_FALSE(wifiPtr->isConnectionInProgress());
}

void test_low_heap_defers_connection_until_retry_tick(void) {
    // Standalone — no begin(), so the guard path owns every observable.
    WifiComponent wifi("Net", "pw");
    const auto& st = HAL::WiFiImpl::stubWifiState();

    HAL::Platform::setFreeHeapForTest(2000);  // below the 2500 connect guard
    wifi.setCredentials("Net2", "pw2", true);

    TEST_ASSERT_EQUAL_UINT(0, st.connectCalls);
    TEST_ASSERT_FALSE(wifi.isConnectionInProgress());

    // "Will retry on next reconnectTimer tick" (Wifi.h:948) — heap recovers,
    // 5 s pass, the deferred connect happens.
    HAL::Platform::resetFreeHeapForTest();
    HAL::Platform::advanceMillisForTest(5001);
    wifi.loop();

    TEST_ASSERT_EQUAL_UINT(1, st.connectCalls);
    TEST_ASSERT_EQUAL_STRING("Net2", st.lastConnectSSID.c_str());
    TEST_ASSERT_TRUE(wifi.isConnectionInProgress());
}

// ============================================================================
// STA fallback timer
// ============================================================================

void test_fallback_arms_at_low_heap_boot(void) {  // F1
    buildStaFixture();
    armFallbackAt3000();
    // AP torn down for the attempt → the UI heard about it.
    TEST_ASSERT_EQUAL_INT(1, (int)apEvents.size());
    TEST_ASSERT_FALSE(apEvents[0]);
}

void test_fallback_success_stays_sta_only_when_heap_low(void) {  // F2
    buildStaFixture();
    armFallbackAt3000();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    HAL::WiFiImpl::setConnectedForTest(true);
    HAL::Platform::advanceMillisForTest(1);
    unsigned startBefore = st.startAPCalls;
    testCore->loop();

    // Heap 3000 ≤ 6500: the AP is NOT restarted — WebUI keeps its 4 KB.
    TEST_ASSERT_EQUAL_UINT(startBefore, st.startAPCalls);
    TEST_ASSERT_EQUAL_INT((int)Mode::Station, (int)HAL::WiFiHAL::getMode());
    TEST_ASSERT_EQUAL_INT((int)ComponentStatus::Success, (int)wifiPtr->getLastStatus());
    TEST_ASSERT_EQUAL_INT(1, (int)staEvents.size());
    TEST_ASSERT_TRUE(staEvents[0]);
}

void test_fallback_success_restarts_ap_when_heap_allows(void) {  // F3
    buildStaFixture();
    armFallbackAt3000();  // phase 1 — heap 20000 here would never arm (review finding 1)
    const auto& st = HAL::WiFiImpl::stubWifiState();

    HAL::Platform::setFreeHeapForTest(20000);  // > 6500: AP+STA affordable now
    HAL::WiFiImpl::setStartAPResultForTest(true);
    HAL::WiFiImpl::setConnectedForTest(true);
    HAL::Platform::advanceMillisForTest(1);
    unsigned startBefore = st.startAPCalls;
    testCore->loop();

    TEST_ASSERT_EQUAL_UINT(startBefore + 1, st.startAPCalls);
    TEST_ASSERT_EQUAL_STRING("FallAP", st.apSSID.c_str());
    TEST_ASSERT_EQUAL_INT((int)Mode::StationAndAP, (int)HAL::WiFiHAL::getMode());
    // Sequence: disabled by the arming teardown, re-enabled on STA's channel.
    TEST_ASSERT_EQUAL_INT(2, (int)apEvents.size());
    TEST_ASSERT_FALSE(apEvents[0]);
    TEST_ASSERT_TRUE(apEvents[1]);
}

void test_fallback_timeout_restores_ap_and_saves_config(void) {  // F4
    buildStaFixture();
    wifiPtr->setConfigSaveCallback(captureConfigSave);
    armFallbackAt3000();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    unsigned startBefore = st.startAPCalls;
    HAL::Platform::advanceMillisForTest(30001);  // past the 30 s fallback window
    testCore->loop();

    TEST_ASSERT_EQUAL_UINT(startBefore + 1, st.startAPCalls);
    TEST_ASSERT_EQUAL_STRING("FallAP", st.apSSID.c_str());
    TEST_ASSERT_EQUAL_INT((int)Mode::AccessPoint, (int)HAL::WiFiHAL::getMode());
    TEST_ASSERT_FALSE(wifiPtr->isWifiEnabled());
    // The anti-boot-loop save: autoConnect=false so the next boot does not
    // retry a dead STA forever, enableAP=true so the device stays reachable.
    TEST_ASSERT_TRUE(configSaved);
    TEST_ASSERT_FALSE(savedConfig.autoConnect);
    TEST_ASSERT_TRUE(savedConfig.enableAP);
    TEST_ASSERT_EQUAL_STRING("Net", savedConfig.ssid.c_str());
    // AP back up → the UI heard disabled (arming) then enabled (restore),
    // and network/ready re-announced the AP address.
    TEST_ASSERT_EQUAL_INT(2, (int)apEvents.size());
    TEST_ASSERT_TRUE(apEvents[1]);
    TEST_ASSERT_EQUAL_INT(1, (int)readyPayloads.size());
    TEST_ASSERT_EQUAL_STRING("0.0.0.0", readyPayloads[0].c_str());
}

void test_ap_client_low_heap_reboots_to_sta(void) {  // F5
    buildStaFixture();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    WifiConfig cfg;
    cfg.ssid = "Net";
    cfg.password = "pw";
    cfg.autoConnect = true;
    cfg.enableAP = true;
    cfg.apSSID = "FallAP";
    cfg.apPassword = "appw";
    wifiPtr->setConfig(cfg);

    HAL::WiFiImpl::setAPStationCountForTest(1);  // a browser is on the AP
    HAL::Platform::setFreeHeapForTest(3000);
    unsigned stopBefore = st.stopAPCalls;
    testCore->loop();

    // Nothing is torn down while the client is connected — the reboot is the
    // whole mechanism (STA needs more heap than a live AP+HTTP can spare).
    TEST_ASSERT_EQUAL_UINT(stopBefore, st.stopAPCalls);
    TEST_ASSERT_EQUAL_UINT(0, HAL::Platform::restartCountForTest);

    HAL::Platform::advanceMillisForTest(1500);  // the deferred-reboot window
    testCore->loop();
    // Per-fire, not latched: a third loop after another 1500 ms would read 2.
    TEST_ASSERT_EQUAL_UINT(1, HAL::Platform::restartCountForTest);
}

void test_ultra_low_heap_guard_disables_sta(void) {  // F6
    // Standalone, no begin(): the guard path must own every observable
    // (review finding 3 — loop() discards updateWifiMode()'s return).
    WifiComponent wifi("Net", "pw");
    wifi.setConfigSaveCallback(captureConfigSave);
    const auto& st = HAL::WiFiImpl::stubWifiState();

    HAL::Platform::setFreeHeapForTest(1500);  // below the 2000 hard floor
    TEST_ASSERT_FALSE(wifi.enableWifi(true));

    TEST_ASSERT_FALSE(wifi.isWifiEnabled());
    TEST_ASSERT_TRUE(configSaved);
    TEST_ASSERT_FALSE(savedConfig.autoConnect);
    // ANY WiFi SDK call may crash at this heap — the guard's contract is that
    // it makes none.
    TEST_ASSERT_EQUAL_UINT(0, st.connectCalls);
    TEST_ASSERT_EQUAL_UINT(0, st.startAPCalls);
    TEST_ASSERT_EQUAL_UINT(0, st.stopAPCalls);
    TEST_ASSERT_EQUAL_UINT(0, st.disconnectCalls);
    TEST_ASSERT_EQUAL_UINT(0, st.disconnectAndOffCalls);
    TEST_ASSERT_EQUAL_INT((int)Mode::Off, (int)HAL::WiFiHAL::getMode());
}

void test_constrained_heap_channel_sync_no_immediate_ap(void) {  // F7
    buildStaFixture();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    WifiConfig cfg;
    cfg.ssid = "Net";
    cfg.password = "pw";
    cfg.autoConnect = true;
    cfg.enableAP = true;
    cfg.apSSID = "FallAP";
    cfg.apPassword = "appw";
    wifiPtr->setConfig(cfg);

    HAL::Platform::setFreeHeapForTest(8000);  // in [3500, 10000): single-radio channel sync
    unsigned stopBefore = st.stopAPCalls;
    unsigned startBefore = st.startAPCalls;
    testCore->loop();

    // AP stops first so STA can find the router's channel; the AP returns via
    // the fallback success handler, not here — that is F3's branch.
    TEST_ASSERT_EQUAL_UINT(stopBefore + 1, st.stopAPCalls);
    TEST_ASSERT_EQUAL_UINT(startBefore, st.startAPCalls);
    TEST_ASSERT_EQUAL_INT((int)Mode::Station, (int)HAL::WiFiHAL::getMode());
}

void test_high_heap_direct_ap_sta(void) {  // F8
    buildStaFixture();
    const auto& st = HAL::WiFiImpl::stubWifiState();
    HAL::WiFiImpl::setStartAPResultForTest(true);

    WifiConfig cfg;
    cfg.ssid = "Net";
    cfg.password = "pw";
    cfg.autoConnect = true;
    cfg.enableAP = true;
    cfg.apSSID = "FallAP";
    cfg.apPassword = "appw";
    wifiPtr->setConfig(cfg);

    // Default heap 65536 ≥ 10000: dual mode directly, no AP interruption.
    unsigned startBefore = st.startAPCalls;
    unsigned stopBefore = st.stopAPCalls;
    testCore->loop();

    TEST_ASSERT_EQUAL_UINT(startBefore + 1, st.startAPCalls);
    TEST_ASSERT_EQUAL_UINT(stopBefore, st.stopAPCalls);
    TEST_ASSERT_EQUAL_STRING("FallAP", st.apSSID.c_str());
    TEST_ASSERT_EQUAL_INT((int)Mode::StationAndAP, (int)HAL::WiFiHAL::getMode());
    TEST_ASSERT_EQUAL_INT(1, (int)apEvents.size());
    TEST_ASSERT_TRUE(apEvents[0]);
}

// ============================================================================
// AP mode
// ============================================================================

void test_begin_empty_ssid_starts_autogenerated_open_ap(void) {  // A1
    testCore = new Core();
    subscribeAll();
    auto wifi = std::make_unique<WifiComponent>("", "");
    wifiPtr = wifi.get();
    testCore->addComponent(std::move(wifi));
    testCore->begin();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    TEST_ASSERT_EQUAL_UINT(1, st.startAPCalls);
    // Stub MAC 00:00:00:00:00:00 → colons stripped → substring(6) → "000000".
    TEST_ASSERT_EQUAL_STRING("DomoticsCore-000000", st.apSSID.c_str());
    TEST_ASSERT_TRUE(st.lastAPPasswordWasNull);  // open network
    TEST_ASSERT_EQUAL_INT((int)Mode::AccessPoint, (int)HAL::WiFiHAL::getMode());
    TEST_ASSERT_TRUE(wifiPtr->isAPEnabled());
    TEST_ASSERT_FALSE(wifiPtr->isWifiEnabled());

    testCore->loop();  // begin() queues, the first loop dispatches
    TEST_ASSERT_EQUAL_INT(1, (int)apEvents.size());
    TEST_ASSERT_TRUE(apEvents[0]);
    TEST_ASSERT_EQUAL_INT(1, (int)readyPayloads.size());
    TEST_ASSERT_EQUAL_STRING("0.0.0.0", readyPayloads[0].c_str());
}

void test_begin_empty_ssid_preconfigured_ap(void) {  // A2
    testCore = new Core();
    subscribeAll();
    auto wifi = std::make_unique<WifiComponent>("", "");
    wifiPtr = wifi.get();
    // Pre-begin, like System does with its deviceName-based SSID. This call
    // itself runs updateWifiMode() and starts the AP once already — begin()'s
    // preconfigured branch is the second startAP. Deltas, not totals.
    wifiPtr->enableAP("MyAP", "appw", true);
    const auto& st = HAL::WiFiImpl::stubWifiState();
    unsigned afterEnable = st.startAPCalls;

    testCore->addComponent(std::move(wifi));
    testCore->begin();

    TEST_ASSERT_EQUAL_UINT(afterEnable + 1, st.startAPCalls);
    TEST_ASSERT_EQUAL_STRING("MyAP", st.apSSID.c_str());
    TEST_ASSERT_FALSE(st.lastAPPasswordWasNull);
    TEST_ASSERT_EQUAL_INT((int)Mode::AccessPoint, (int)HAL::WiFiHAL::getMode());
    TEST_ASSERT_EQUAL_INT((int)ComponentStatus::Success, (int)wifiPtr->getLastStatus());
    // NOT asserted: isWifiEnabled() false — the pre-begin enableAP already
    // forced it through the stale-config guard; asserting it here would pin
    // the wrong line (review finding 7).
}

void test_ap_only_update_skips_restart_when_already_running(void) {  // A3
    HAL::WiFiImpl::setStartAPResultForTest(true);  // the skip check reads getAPSSID(), which needs a live AP
    testCore = new Core();
    subscribeAll();
    auto wifi = std::make_unique<WifiComponent>("", "");
    wifiPtr = wifi.get();
    wifiPtr->enableAP("MyAP", "appw", true);
    testCore->addComponent(std::move(wifi));
    testCore->begin();
    testCore->loop();
    const auto& st = HAL::WiFiImpl::stubWifiState();

    // Same AP again through the WebUI-save path (setConfig → deferred update).
    unsigned startBefore = st.startAPCalls;
    unsigned disconnectBefore = st.disconnectCalls;
    WifiConfig cfg;
    cfg.ssid = "";
    cfg.autoConnect = false;
    cfg.enableAP = true;
    cfg.apSSID = "MyAP";
    cfg.apPassword = "appw";
    wifiPtr->setConfig(cfg);
    testCore->loop();

    // The AP is already up with that SSID: no restart, no disconnect — the
    // brief AP dropout this branch prevents is the point.
    TEST_ASSERT_EQUAL_UINT(startBefore, st.startAPCalls);
    TEST_ASSERT_EQUAL_UINT(disconnectBefore, st.disconnectCalls);
    TEST_ASSERT_TRUE(st.apActive);
}

void test_stale_config_wifi_enabled_without_ssid_is_disabled(void) {  // A4
    WifiComponent wifi;  // standalone
    WifiConfig cfg;
    cfg.ssid = "";
    cfg.autoConnect = true;  // the stale half-config a crash can leave behind
    cfg.enableAP = false;
    wifi.setConfig(cfg);
    wifi.loop();  // deferred updateWifiMode runs here

    TEST_ASSERT_FALSE(wifi.isWifiEnabled());
    // The guard's other half: shouldConnect = false, observable through
    // getConfig().autoConnect. (A connectCalls assert stood here first and was
    // vacuous — no rewrite of the guard can make updateWifiMode() connect.)
    TEST_ASSERT_FALSE(wifi.getConfig().autoConnect);
}

// ============================================================================
// Runner
// ============================================================================

int main(int argc, char** argv) {
    UNITY_BEGIN();

    // Reconnection
    RUN_TEST(test_reconnect_success_emits_events);
    RUN_TEST(test_connection_timeout_then_same_tick_retry);
    RUN_TEST(test_disconnect_stops_reconnection);
    RUN_TEST(test_low_heap_defers_connection_until_retry_tick);

    // STA fallback timer
    RUN_TEST(test_fallback_arms_at_low_heap_boot);
    RUN_TEST(test_fallback_success_stays_sta_only_when_heap_low);
    RUN_TEST(test_fallback_success_restarts_ap_when_heap_allows);
    RUN_TEST(test_fallback_timeout_restores_ap_and_saves_config);
    RUN_TEST(test_ap_client_low_heap_reboots_to_sta);
    RUN_TEST(test_ultra_low_heap_guard_disables_sta);
    RUN_TEST(test_constrained_heap_channel_sync_no_immediate_ap);
    RUN_TEST(test_high_heap_direct_ap_sta);

    // AP mode
    RUN_TEST(test_begin_empty_ssid_starts_autogenerated_open_ap);
    RUN_TEST(test_begin_empty_ssid_preconfigured_ap);
    RUN_TEST(test_ap_only_update_skips_restart_when_already_running);
    RUN_TEST(test_stale_config_wifi_enabled_without_ssid_is_disabled);

    return UNITY_END();
}
