[env]
framework = arduino
lib_archive = false
lib_ldf_mode = chain
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3
lib_deps =
    file://../../../../DomoticsCore-Core
    file://../../../../DomoticsCore-LED
    file://../../../../DomoticsCore-RemoteConsole
    file://../../../../DomoticsCore-Wifi
    file://../../../../DomoticsCore-System
    file://../../../../DomoticsCore-Storage
    file://../../../../DomoticsCore-SystemInfo
    bblanchon/ArduinoJson@^7.0.4

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
board_build.filesystem = littlefs
upload_port = /dev/ttyUSB1
build_flags = ${env.build_flags} -std=gnu++17
build_unflags = -std=gnu++11

[env:esp32dev]
platform = espressif32
board = esp32dev
upload_port = /dev/ttyUSB0
build_flags = ${env.build_flags} -std=gnu++14 -DSTART_STEP=3
build_unflags = -std=gnu++11

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
upload_port = /dev/ttyACM0
build_flags = ${env.build_flags} -std=gnu++14 -DSTART_STEP=1 -DPROBE_MAGIC=0x0B5C0DE7 -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags = -std=gnu++11
