[env]
framework = arduino
lib_archive = false
lib_ldf_mode = chain
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3 -I../../../..
extra_scripts = pre:../../../../DomoticsCore-WebUI/embed_webui.py
lib_deps =
    file://../../../../DomoticsCore-Core
    file://../../../../DomoticsCore-LED
    file://../../../../DomoticsCore-RemoteConsole
    file://../../../../DomoticsCore-Wifi
    file://../../../../DomoticsCore-System
    file://../../../../DomoticsCore-WebUI
    file://../../../../DomoticsCore-NTP
    file://../../../../DomoticsCore-Storage
    file://../../../../DomoticsCore-MQTT
    file://../../../../DomoticsCore-OTA
    file://../../../../DomoticsCore-SystemInfo
    file://../../../../DomoticsCore-HomeAssistant
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
lib_ignore = ESPAsyncTCP, RPAsyncTCP

[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = min_spiffs.csv
upload_port = /dev/ttyUSB0
build_flags = ${env.build_flags} -std=gnu++14 -DLOOPMAX_WDT=0
build_unflags = -std=gnu++11

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.partitions = min_spiffs.csv
upload_port = /dev/ttyACM0
build_flags = ${env.build_flags} -std=gnu++17 -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags = -std=gnu++11
